### ISSUE TITLE
Coordinated Omission in ping pong latency measurement

### ISSUE THREAD

**Issue by nitsanw** [benalexau/rpc-bench#1]
Because the measurements are back to back it allows the system under test to block the load generator. To avoid the coordination we need to set the ping frequency and split the send and receive threads so that we have a close to constant pace sender (or at any rate a sender with a notion of schedule) and a busy receiver. Because the send and receive are non-blocking the same observation is not necessarily true for the streaming case, but I've not looked.

**Comment by bp-alex** [comment]
For clarification, both client and server execute in separate JVMs and enter via their own main methods. The main user thread ultimately enters a loop that sends one ping message and then awaits delivery of the pong message before continuing the loop iteration. This means at no time is there more than one ping or pong outstanding. This approach was based on the Aeron ping-pong sample. gRPC and Aeron both use separate threads or processes to perform the network transfers, and in gRPC's case, the (de-)serialization.

For gRPC the main user thread uses a `CountDownLatch` to await the receipt of each individual pong. The main user thread therefore sends the ping and quickly enters the latch, with gRPC's thread responsible for the eventual `StreamObserver.on*` callback invocation. Once the `StreamInvoker.on*` callback is invoked, it decrements the latch and allows the main user thread to continue the loop.

For Aeron the main user thread sends the ping and then uses `Subscription.poll` until the pong reply is received. While waiting for the pong, it uses Agrona's busy spin `IdleStrategy`. The separate `LowLatencyMediaDriver` process performs the actual network transfers. The main user thread in Aeron's case performs the SBE (de-)serialization.

I added some thread parking in commit 4401cd9 and updated the reports to illustrate the inter-run variations.

Would you mind elaborating on where the concern is, or maybe send over a pull request for me to take a look at?

**Comment by nitsanw** [comment]
I think I understand the threading model, and I realize you are not the originator of this measurement method. Lets see if I can clarify the issue.
If we aim to measure the responsiveness of a system to arbitrary requests we need the load generator to measure independently from the system under test, the same way an arbitrary client would. When we have a synchronous req/res interaction the load generating thread is  blocked from starting a new request while waiting for the previous response. Imagine we set out to send a request every millisecond, but because one request took 100ms we did not send the 99 requests blocked behind it. Our measurement would include one bad latency event, but will ignore the backed up requests getting delayed. This is coordinated omission.
Since the Aeron API is not synchronous you can work around this issue in 2 ways (and I suggest you apply both):
- Compute a schedule and measure from it. Have the ping rate set as a parameter and start measurement from the intended send time rather than the actual. In fact, I recommend you capture both in 2 histograms. To increase timing accuracy you might choose to spin wait for the next send event (e.g. "while(nanoTime() < sendTime){};") rather than use a block/park/sleep type API which tends to have more variance.
- Use a separate thread for receiving the replies. This will allow you to avoid timing issues due to receives blocking the sends and actually have a best effort at sending on time. It also reflects correct API usage better IMO.

If I have time I will submit a patch, but I'm currently quite busy so it might take a bit.

**Comment by bp-alex** [comment]
Thanks for clarifying. This improvement is confined to the clients, so it shouldn't be too hard to make. I guess the new problem becomes determining what is a reasonable fixed schedule for the ping rate, particularly given we're seeing such substantial difference between the implementations and gRPC is known to allocate unlimited buffers when the user thread makes faster progress than the sending thread (and in turn the excessive allocation costs slow down the JVM). Any thoughts on what would be reasonable having regard to the sort of latency ballparks we're seeing with the Aeron-inspired ping-pong approach?

**Comment by nitsanw** [comment]
I'd say default to 1000/s and let people have a choice. Most systems can respond in less than a ms but see multi-ms hiccups regularly.
For comparison sake it would make sense to look at different loads: 100/s, 1000/s, 10000/s
Or you can explore the space any way you like. All systems break at some point and finding that breaking point is informative. Automatically finding the breaking point is hard though, so I'd not tackle it with this tool, rather let people automate on top of it if they like.

**Comment by bp-alex** [comment]
I've updated the code and run a new benchmark. I went with 10,000/second given it would take too long to run otherwise, and both gRPC and Aeron can easily cope with 10,000/second. 

I'll close this ticket now, but please comment if you have any further suggestions.

**Comment by nitsanw** [comment]
LGTM :-)!!!
Can you post new results? makes an interesting CO story

**Comment by bp-alex** [comment]
I posted the most recent results in the [24 October 2016 report](https://github.com/benalexau/rpc-bench/blob/master/results/20161024/README.md).
